name: Just Build Docker

on:
  pull_request:
    branches: [ "main" ]

jobs:
  just-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Yarn install and build
        run: |
          yarn install
          yarn build
      - name: Try Building image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ secrets.APP_IMAGE }}
          build-args: |
            S3_PUBLIC_ENDPOINT: ${{ secrets.S3_PUBLIC_ENDPOINT }}
